import { createFileRoute } from "@tanstack/react-router";
import { PageShell, SectionIntro } from "@/components/site-shell";
import { routeMeta, tracks } from "@/lib/content";
import { images } from "@/lib/media";

export const Route = createFileRoute("/archive")({ head: () => routeMeta("Edition 1 Archive — HealthXHer", "A concise archive of HealthXHer Edition 1: its challenge tracks, people, partners and impact."), component: ArchivePage });

function ArchivePage() {
  return <PageShell><div className="page-enter">
    <section className="soft-section py-20 md:py-28"><div className="site-container"><p className="eyebrow">Archive · Edition 1</p><h1 className="max-w-4xl font-display text-5xl leading-tight md:text-7xl">The first chapter of HealthXHer.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">A multidisciplinary hackathon that brought students, mentors and partners together around practical challenges in women&apos;s health.</p><p className="mt-6"><a className="text-sm font-semibold underline-offset-4 hover:underline" href="/archive/v1/index.html">Open the original first-edition site</a></p><div className="mt-12 grid gap-4 sm:grid-cols-3">{[["24","teams"],["18","mentors"],["12","insights"]].map(([n,label]) => <div key={label} className="border-t border-primary pt-4"><span className="font-display text-5xl">{n}</span><p className="mt-2 text-sm uppercase tracking-widest text-muted-foreground">{label}</p></div>)}</div></div></section>
    <section className="site-container py-24"><div className="grid gap-10 md:grid-cols-2 md:items-end"><SectionIntro eyebrow="The challenge" title="Three tracks shaped the work."/><p className="leading-7 text-muted-foreground">Edition 1 focused attention on evidence and delivery gaps where interdisciplinary thinking could unlock more equitable outcomes.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{tracks.map((track) => <article key={track.number} className="rounded-xl bg-muted p-7"><span className="font-display text-4xl text-accent">{track.number}</span><h2 className="mt-6 font-display text-2xl">{track.title}</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">{track.short}</p></article>)}</div></section>
    <section className="bg-primary py-20 text-primary-foreground"><div className="site-container grid items-center gap-10 md:grid-cols-2"><div><p className="eyebrow text-primary-foreground/60">Partners</p><h2 className="section-title">Industry expertise met emerging talent.</h2><p className="mt-6 max-w-xl leading-7 text-primary-foreground/70">AstraZeneca supported the first edition with challenge context, mentoring and opportunities for teams to share what they learned.</p></div><div className="rounded-xl bg-card p-12"><img src={images.azLogo} alt="AstraZeneca" className="mx-auto max-h-24 w-full object-contain"/></div></div></section>
    <section className="site-container py-24"><SectionIntro centered eyebrow="Moments from Edition 1" title="People, ideas and a shared sense of possibility."/><div className="mt-12 grid auto-rows-[15rem] gap-4 md:grid-cols-2 lg:grid-cols-3"><img src={images.gallery01} alt="Edition 1 presentation" className="h-full w-full rounded-xl object-cover grayscale lg:row-span-2"/><img src={images.gallery03} alt="Edition 1 collaboration" className="h-full w-full rounded-xl object-cover grayscale"/><img src={images.gallery06} alt="Edition 1 team discussion" className="h-full w-full rounded-xl object-cover grayscale"/><img src={images.gallery08} alt="Edition 1 participants" className="h-full w-full rounded-xl object-cover grayscale md:col-span-2"/></div></section>
  </div></PageShell>;
}