import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, Lightbulb, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CtaBand, PageShell, SectionIntro } from "@/components/site-shell";
import { routeMeta, tracks } from "@/lib/content";
import eventImage from "@/assets/gallery-01.JPG.asset.json";

export const Route = createFileRoute("/hackathon")({ head: () => routeMeta("HealthXHer Hackathon — Edition 2", "Explore Edition 2 of the interdisciplinary HealthXHer hackathon, its challenges, format and opportunities."), component: HackathonPage });

function HackathonPage() {
  return <PageShell><div className="page-enter">
    <section className="site-container grid min-h-[38rem] items-center gap-12 py-16 lg:grid-cols-[1fr_.9fr]"><div><p className="eyebrow">Edition 2 · 2027</p><h1 className="font-display text-5xl leading-tight md:text-7xl">Ideas become evidence when disciplines meet.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">A focused innovation programme connecting early talent with healthcare, research, industry and policy to redesign the systems shaping women&apos;s health.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild><a href="mailto:healthxher@gmail.com?subject=Edition%202%20application">Apply to Edition 2</a></Button><Button asChild variant="outline"><a href="#format">See how it works</a></Button></div></div><img src={eventImage.url} alt="Participants presenting at the HealthXHer hackathon" className="aspect-[4/5] w-full rounded-xl object-cover grayscale" /></section>
    <section id="format" className="soft-section py-24"><div className="site-container"><SectionIntro centered eyebrow="The format" title="A collaborative sprint from question to concept." /><div className="mt-14 grid gap-5 md:grid-cols-3">{[[Users,"Build the team","Four people. Different disciplines. One shared challenge."],[Lightbulb,"Shape the concept","Work with mentors to turn evidence gaps into practical ideas."],[CalendarDays,"Share the outcome","Present a prototype, design document or comprehensive concept."]].map(([Icon,title,copy]) => { const I = Icon as typeof Users; return <article key={title as string} className="rounded-xl bg-card p-8"><I className="size-7 text-accent"/><h2 className="mt-8 font-display text-2xl">{title as string}</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">{copy as string}</p></article>; })}</div></div></section>
    <section className="bg-primary py-24 text-primary-foreground"><div className="site-container"><SectionIntro eyebrow="Edition 1 tracks" title="Three challenges. One mission." copy="The first edition's briefs show the breadth of systems-level thinking HealthXHer brings together."/><div className="mt-14 grid gap-4 md:grid-cols-3">{tracks.map((track) => <article key={track.number} className="rounded-xl border border-primary-foreground/20 p-7"><span className="font-display text-5xl text-primary-foreground/25">{track.number}</span><h2 className="mt-7 font-display text-2xl">{track.title}</h2><p className="mt-4 text-sm leading-6 text-primary-foreground/65">{track.short}</p><a className="mt-8 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-widest" href="mailto:healthxher@gmail.com?subject=Challenge%20brief">Request brief <ArrowRight size={14}/></a></article>)}</div></div></section>
    <section className="site-container py-24"><div className="grid gap-14 md:grid-cols-2"><SectionIntro eyebrow="Schedule" title="The next chapter starts in 2027." copy="Applications open on 19 January. The complete programme, host cities and in-person dates will be shared with selected participants."/><div><p className="eyebrow">Recognition</p><h2 className="font-display text-3xl">What participants take forward</h2><ul className="mt-7 divide-y divide-border border-y border-border">{["Expert feedback from industry leaders","Cross-university networks","Hands-on workshops and mentoring","Official participation certification","A platform for practical women's health ideas"].map((item) => <li key={item} className="py-4">{item}</li>)}</ul></div></div></section>
    <CtaBand />
  </div></PageShell>;
}